declare const _default: ({
    type: string;
    input: boolean;
    key: string;
    label: string;
    placeholder: string;
    weight: number;
    tooltip: string;
    validate: {
        required: boolean;
    };
    defaultValue?: undefined;
    rows?: undefined;
    editor?: undefined;
    as?: undefined;
    description?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    defaultValue: string;
    placeholder: string;
    weight: number;
    tooltip: string;
    validate?: undefined;
    rows?: undefined;
    editor?: undefined;
    as?: undefined;
    description?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    placeholder: string;
    weight: number;
    rows: number;
    editor: string;
    as: string;
    tooltip: string;
    validate?: undefined;
    defaultValue?: undefined;
    description?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    placeholder: string;
    description: string;
    weight: number;
    rows: number;
    editor: string;
    tooltip: string;
    validate?: undefined;
    defaultValue?: undefined;
    as?: undefined;
})[];
export default _default;
