version: "2"
exclude_patterns:
  - components/
  - config/
  - dist/
  - features/
  - script/
  - Tests/
  - "**/*.d.ts"
  - "**/*_test.go"
  - "**/db/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
plugins:
  csslint:
    enabled: true
  editorconfig:
    enabled: true
    checks:
      END_OF_LINE:
        enabled: false
      INDENTATION_SPACES:
        enabled: false
      INDENTATION_SPACES_AMOUNT:
        enabled: false
      TRAILINGSPACES:
        enabled: false
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: app/.eslintrc.js
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD029:
        enabled: false
      MD046:
        enabled: false
  nodesecurity:
    enabled: true
  sass-lint:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 6
  method-lines:
    config:
      threshold: 40
  file-lines:
    config:
      threshold: 500
