version: "3.9"
volumes:
  postgres_kc_data:
    driver: local
networks:
  common-network:
    driver: bridge
services:
  postgres:
    image: postgres:14.2
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chefs
    networks:
      - common-network
  chefs-keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    volumes:
      - type: bind
        source: ./docker/imports/keycloak/realm-export.json
        target: /tmp/realm-export.json
        read_only: true
    ports:
      - 8082:8082
    networks:
      - common-network
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    restart: unless-stopped
    command:
      - "start-dev"
      - "--http-port=8082"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
