{{- $secretName := (.Values.ess.nats.secret.name) }}
{{- $sysadminPwdValue := randAlphaNum 32 | b64enc }}
{{- $adminPwdValue := randAlphaNum 32 | b64enc }}
{{- $chefsPwdValue := randAlphaNum 32 | b64enc }}
{{- $chefsconsumerPwdValue := randAlphaNum 32 | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  sysadmin_pwd: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "sysadmin_pwd" "defaultValue" $sysadminPwdValue "context" $) }}
  admin_pwd: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "admin_pwd" "defaultValue" $adminPwdValue "context" $) }}
  chefs_pwd: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "chefs_pwd" "defaultValue" $chefsPwdValue "context" $) }}
  chefsconsumer_pwd: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "chefsconsumer_pwd" "defaultValue" $chefsconsumerPwdValue "context" $) }}
  