---
apiVersion: v1
kind: Template
labels:
  app: "${APP_NAME}-${JOB_NAME}"
  template: "${REPO_NAME}-formio-dc-template"
metadata:
  name: "${REPO_NAME}-formio-dc"
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "${APP_NAME}-formio-${JOB_NAME}"
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: "${APP_NAME}-${JOB_NAME}"
        deploymentconfig: "${APP_NAME}-formio-${JOB_NAME}"
        role: formio
      strategy:
        type: Rolling
        resources: {}
        rollingParams:
          timeoutSeconds: 600
      template:
        metadata:
          labels:
            app: "${APP_NAME}-${JOB_NAME}"
            deploymentconfig: "${APP_NAME}-formio-${JOB_NAME}"
            role: formio
        spec:
          containers:
            - image: docker-registry.default.svc:5000/${NAMESPACE}/${REPO_NAME}-formio:latest
              imagePullPolicy: IfNotPresent
              livenessProbe:
                tcpSocket:
                  port: 3001
                failureThreshold: 3
                # httpGet:
                #   path: "/"
                #   port: 3001
                #   scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 1
              name: formio
              ports:
                - containerPort: 3001
                  protocol: TCP
              readinessProbe:
                tcpSocket:
                  port: 3001
                failureThreshold: 3
                # httpGet:
                #   path: "/"
                #   port: 3001
                #   scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              env:
                - name: NODE_ENV
                  value: production
                - name: DEBUG
                  value: formio:*
                - name: NODE_CONFIG
                  value: '{"mongo": "mongodb://app:Uf5tF4QQ8WlAJ1R8WPv8YEpwt5dPdCCQ@mongodb-${JOB_NAME}:27017/app"}'
                - name: NO_INSTALL
                  value: "true"
                - name: ROOT_EMAIL
                  value: admin@example.com
                - name: ROOT_PASSWORD
                  value: CHANGEME
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - formio
            from:
              kind: ImageStreamTag
              name: "${REPO_NAME}-formio:latest"
              namespace: "${NAMESPACE}"
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${APP_NAME}-formio-${JOB_NAME}"
    spec:
      ports:
        - name: 3001-tcp
          port: 3001
          protocol: TCP
          targetPort: 3001
      selector:
        app: "${APP_NAME}-${JOB_NAME}"
        deploymentconfig: "${APP_NAME}-formio-${JOB_NAME}"
        role: formio
      sessionAffinity: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${APP_NAME}-formio-${JOB_NAME}"
    spec:
      host: "${ROUTE_HOST}"
      port:
        targetPort: 3001-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${APP_NAME}-formio-${JOB_NAME}"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: APP_NAME
    description: Application name
    displayName: Application name
    required: true
  - name: ROUTE_HOST
    description: The host the route will use to expose service outside cluster
    displayName: Route host
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'wfezkf-dev')
    displayName: Target Namespace
    required: true
  - name: REPO_NAME
    description: Application repository name
    displayName: Repository Name
    required: true
  - name: CPU_LIMIT
    description: Limit Peak CPU per pod (in millicores ex. 1000m)
    displayName: CPU Limit
    value: 250m
  - name: CPU_REQUEST
    description: Requested CPU per pod (in millicores ex. 500m)
    displayName: CPU Request
    value: 100m
  - name: MEMORY_LIMIT
    description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
    displayName: Memory Limit
    value: 1Gi
  - name: MEMORY_REQUEST
    description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
    displayName: Memory Request
    value: 256Mi
