import orgbook from './OrgBook/Component';
import recap from './ReCaptcha/Component';
import simplebtnreset from './SimpleButtonReset/Component';
import simplebtnsubmit from './SimpleButtonSubmit/Component';
import simplecheckbox from './SimpleCheckbox/Component';
import simplecheckboxes from './SimpleCheckboxes/Component';
import simplecols2 from './SimpleColumns2/Component';
import simplecols3 from './SimpleColumns3/Component';
import simplecols4 from './SimpleColumns4/Component';
import simplecontent from './SimpleContent/Component';
import simpledatetime from './SimpleDateTime/Component';
import simpleday from './SimpleDay/Component';
import simpleemail from './SimpleEmail/Component';
import simplefieldset from './SimpleFieldSet/Component';
import simplefile from './SimpleFile/Component';
import simpleheading from './SimpleHeading/Component';
import simplenumber from './SimpleNumber/Component';
import simplepanel from './SimplePanel/Component';
import simpleparagraph from './SimpleParagraph/Component';
import simplephonenumber from './SimplePhoneNumber/Component';
import simpleradios from './SimpleRadios/Component';
import simpleselect from './SimpleSelect/Component';
import simpletabs from './SimpleTabs/Component';
import simpletextarea from './SimpleTextArea/Component';
import simpletextfield from './SimpleTextField/Component';
import simpletime from './SimpleTime/Component';
import simpletextfieldadvanced from './SimpleTextFieldAdvanced/Component';
import simpleemailadvanced from './SimpleEmailAdvanced/Component';
import simpletextareaadvanced from './SimpleTextAreaAdvanced/Component';
import simplenumberadvanced from './SimpleNumberAdvanced/Component';
import simpleurladvanced from './SimpleUrlAdvanced/Component';
import simplephonenumberadvanced from './SimplePhoneNumberAdvanced/Component';
import simpletagsadvanced from './SimpleTagsAdvanced/Component';
import simpleaddressadvanced from './SimpleAddressAdvanced/Component';
import simplepasswordadvanced from './SimplePasswordAdvanced/Component';
import simpledatetimeadvanced from './SimpleDateTimeAdvanced/Component';
import simplecheckboxadvanced from './SimpleCheckboxAdvanced/Component';
import simpledayadvanced from './SimpleDayAdvanced/Component';
import simpletimeadvanced from './SimpleTimeAdvanced/Component';
import simpleselectboxesadvanced from './SimpleSelectBoxesAdvanced/Component';
import simpleselectadvanced from './SimpleSelectAdvanced/Component';
import simplecurrencyadvanced from './SimpleCurrencyAdvanced/Component';
import simpleradioadvanced from './SimpleRadioAdvanced/Component';
import simplesurveyadvanced from './SimpleSurveyAdvanced/Component';
import simplesignatureadvanced from './SimpleSignatureAdvanced/Component';
import simplebuttonadvanced from './SimpleButtonAdvanced/Component';
import bcaddress from './BCAddress/Component';
declare const _default: {
    orgbook: typeof orgbook;
    simplebtnreset: typeof simplebtnreset;
    simplebtnsubmit: typeof simplebtnsubmit;
    simplecheckbox: typeof simplecheckbox;
    simplecheckboxes: typeof simplecheckboxes;
    simplecols2: typeof simplecols2;
    simplecols3: typeof simplecols3;
    simplecols4: typeof simplecols4;
    simplecontent: typeof simplecontent;
    simpledatetime: typeof simpledatetime;
    simpleday: typeof simpleday;
    simpleemail: typeof simpleemail;
    simplefieldset: typeof simplefieldset;
    simplefile: typeof simplefile;
    simpleheading: typeof simpleheading;
    simplenumber: typeof simplenumber;
    simplepanel: typeof simplepanel;
    simpleparagraph: typeof simpleparagraph;
    simplephonenumber: typeof simplephonenumber;
    simpleradios: typeof simpleradios;
    simpleselect: typeof simpleselect;
    simpletabs: typeof simpletabs;
    simpletextarea: typeof simpletextarea;
    simpletextfield: typeof simpletextfield;
    simpletime: typeof simpletime;
    simpletextfieldadvanced: typeof simpletextfieldadvanced;
    simpleemailadvanced: typeof simpleemailadvanced;
    simpletextareaadvanced: typeof simpletextareaadvanced;
    simplenumberadvanced: typeof simplenumberadvanced;
    simpleurladvanced: typeof simpleurladvanced;
    simplephonenumberadvanced: typeof simplephonenumberadvanced;
    simpletagsadvanced: typeof simpletagsadvanced;
    simpleaddressadvanced: typeof simpleaddressadvanced;
    simplepasswordadvanced: typeof simplepasswordadvanced;
    simpledatetimeadvanced: typeof simpledatetimeadvanced;
    simplecheckboxadvanced: typeof simplecheckboxadvanced;
    simpledayadvanced: typeof simpledayadvanced;
    simpletimeadvanced: typeof simpletimeadvanced;
    simpleselectboxesadvanced: typeof simpleselectboxesadvanced;
    simpleselectadvanced: typeof simpleselectadvanced;
    simplecurrencyadvanced: typeof simplecurrencyadvanced;
    simpleradioadvanced: typeof simpleradioadvanced;
    simplesurveyadvanced: typeof simplesurveyadvanced;
    simplesignatureadvanced: typeof simplesignatureadvanced;
    simplebuttonadvanced: typeof simplebuttonadvanced;
    bcaddress: typeof bcaddress;
    recap: typeof recap;
};
export default _default;
