nats:
  config:
    merge:
      authorization:
        default_permissions:
          publish:
            [
              "SANDBOX.*",
              "$JS.API.INFO",
              "$JS.API.CONSUMER.CREATE.*",
              "$JS.API.CONSUMER.CREATE.*.>",
              "$JS.API.CONSUMER.DURABLE.CREATE.*.>",
              "$JS.API.CONSUMER.DELETE.*.>",
              "$JS.API.CONSUMER.INFO.*.>",
              "$JS.API.CONSUMER.LIST.*",
              "$JS.API.CONSUMER.NAMES.*",
              "$JS.API.CONSUMER.MSG.NEXT.*.>",
              "$JS.API.CONSUMER.MSG.NEXT.*.NEW",
              "$JS.API.STREAM.MSG.GET.*",
              "$JS.API.STREAM.INFO.*",
              "$JS.API.STREAM.LIST",
              "$JS.API.STREAM.NAMES",
              "$JS.ACK.*",
              "$JS.ACK.*.>",
            ]
          subscribe: ["PUBLIC.>", "PRIVATE.>", "_INBOX.>"]
        users:
          - user: "admin"
            password: << $ADMIN_PWD >>
            permissions:
              publish: [">"]
              subscribe: [">"]
          - user: "chefs"
            password: << $CHEFS_PWD >>
            permissions:
              publish:
                [
                  "$JS.API.INFO",
                  "$JS.API.STREAM.CREATE.CHEFS",
                  "$JS.API.STREAM.UPDATE.CHEFS",
                  "$JS.API.STREAM.DELETE.CHEFS",
                  "$JS.API.STREAM.INFO.CHEFS",
                  "$JS.API.STREAM.PURGE.CHEFS",
                  "$JS.API.STREAM.LIST",
                  "$JS.API.STREAM.NAMES",
                  "$JS.API.STREAM.MSG.DELETE.CHEFS",
                  "$JS.API.STREAM.MSG.GET.CHEFS",
                  "$JS.API.STREAM.SNAPSHOT.CHEFS",
                  "$JS.API.STREAM.RESTORE.CHEFS",
                  "$JS.API.CONSUMER.CREATE.CHEFS",
                  "$JS.API.CONSUMER.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DURABLE.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DELETE.CHEFS.>",
                  "$JS.API.CONSUMER.INFO.CHEFS.>",
                  "$JS.API.CONSUMER.LIST.CHEFS",
                  "$JS.API.CONSUMER.NAMES.CHEFS",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.>",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.NEW",
                  "$JS.API.STREAM.MSG.GET.CHEFS",
                  "$JS.ACK.CHEFS.>",
                  "PUBLIC.forms.>",
                  "PRIVATE.forms.>",
                ]
              subscribe: ["_INBOX.>"]
          - user: "chefsConsumer" # currently used by health, read-only consumer for CHEFS
            password: << $CHEFSCONSUMER_PWD >>
            permissions:
              publish:
                [
                  "SANDBOX.*",
                  "$JS.API.INFO",
                  "$JS.API.CONSUMER.CREATE.CHEFS",
                  "$JS.API.CONSUMER.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DURABLE.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DELETE.CHEFS.>",
                  "$JS.API.CONSUMER.INFO.CHEFS.>",
                  "$JS.API.CONSUMER.LIST.CHEFS",
                  "$JS.API.CONSUMER.NAMES.CHEFS",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.>",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.NEW",
                  "$JS.API.STREAM.MSG.GET.CHEFS",
                  "$JS.API.STREAM.INFO.CHEFS",
                  "$JS.API.STREAM.LIST",
                  "$JS.API.STREAM.NAMES",
                  "$JS.ACK.CHEFS",
                  "$JS.ACK.CHEFS.>",
                ]
              subscribe: ["PUBLIC.forms.>", "PRIVATE.forms.>", "_INBOX.>"]
          # The following block of nkey users are for read-only CHEFS accounts
          # document beside the NKEY an indication of who (person or Initiative) requested the account
          #
          # These accounts are for CHEFS and should use the CHEFS restricted permissions.
          - nkey: "UCT3KJ7BCOK3ZH5KSAJTHL3WRB5CX2MJ2XMKX2R7FRZUAUYC427TGESZ" # CHEFS read-only, demo.
            permissions:
              publish:
                [
                  "SANDBOX.*",
                  "$JS.API.INFO",
                  "$JS.API.CONSUMER.CREATE.CHEFS",
                  "$JS.API.CONSUMER.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DURABLE.CREATE.CHEFS.>",
                  "$JS.API.CONSUMER.DELETE.CHEFS.>",
                  "$JS.API.CONSUMER.INFO.CHEFS.>",
                  "$JS.API.CONSUMER.LIST.CHEFS",
                  "$JS.API.CONSUMER.NAMES.CHEFS",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.>",
                  "$JS.API.CONSUMER.MSG.NEXT.CHEFS.NEW",
                  "$JS.API.STREAM.MSG.GET.CHEFS",
                  "$JS.API.STREAM.INFO.CHEFS",
                  "$JS.API.STREAM.LIST",
                  "$JS.API.STREAM.NAMES",
                  "$JS.ACK.CHEFS",
                  "$JS.ACK.CHEFS.>",
                ]
              subscribe: ["PUBLIC.forms.>", "PRIVATE.forms.>", "_INBOX.>"]
