ess:
  nginx:
    route:
      ingressPrefix: stream-test
      ingressSuffix: .apps.silver.devops.gov.bc.ca

nats:
  container:
    merge:
      resources:
        limits:
          cpu: 20m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 32Mi

nginx:
  resources:
    limits:
      cpu: 125m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
