---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app.kubernetes.io/component: server
  app.kubernetes.io/instance: ${NAME}
  app.kubernetes.io/managed-by: kubectl
  app.kubernetes.io/name: redash
  app.kubernetes.io/part-of: redash
metadata:
  name: ${NAME}
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-${NAME}-a12c97-tools-to-patroni-master-readonly
    spec:
      podSelector:
        matchLabels:
          cluster-name: master
          role: replica
          statefulset: patroni-master
      ingress:
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: redash
              namespaceSelector:
                matchLabels:
                  environment: tools
                  name: a12c97
      policyTypes:
        - Ingress
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: chefs-redash
