---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: "${NAME}"
  app.kubernetes.io/component: "${NAME}"
  app.kubernetes.io/instance: "${NAME}"
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: redash
  app.kubernetes.io/part-of: "${NAME}"
  template: "${NAME}-secret-template"
metadata:
  name: "${NAME}-secret"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${NAME}-admin"
    stringData:
      REDASH_ADMIN_PASSWORD: ${REDASH_ADMIN_PASSWORD}
      REDASH_ADMIN_USERNAME: ${REDASH_ADMIN_USERNAME}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${NAME}-config"
    stringData:
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${NAME}-postgresql"
      labels:
        app: ${NAME}
      annotations:
        description: Database credentials and name.
        template.openshift.io/expose-database_name: "${.data['POSTGRES_DATABASE']}"
        template.openshift.io/expose-password: "${.data['POSTGRES_PASSWORD']}"
        template.openshift.io/expose-username: "${.data['POSTGRES_USER']}"
    stringData:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${NAME}-redis"
    stringData:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: chefs-redash
  - name: REDASH_ADMIN_USERNAME
    displayName: Redash Administrator Username
    description: The username for the Redash administrator account
    required: true
    value: submit.digital@gov.bc.ca
  - name: REDASH_ADMIN_PASSWORD
    displayName: Redash Administrator Password
    description: The password for the Redash administrator account
    from: "[a-zA-Z0-9]{32}"
    generate: expression
    required: true
  - name: REDASH_COOKIE_SECRET
    displayName: Redash Cookie Secret
    description: A reference to Redash cookie secret
    from: "[a-zA-Z0-9]{32}"
    generate: expression
    required: true
  - name: REDASH_SECRET_KEY
    displayName: Redash Secret Key
    description: A reference to Redash secret key
    from: "[a-zA-Z0-9]{32}"
    generate: expression
    required: true
  - name: POSTGRES_NONROOT_GROUP
    displayName: PostgreSQL non-root group
    description: A group for non-root users
    generate: expression
    from: "group[A-Z0-9]{3}"
    required: true
  - name: POSTGRES_USER
    displayName: PostgreSQL Username
    from: "user[A-Z0-9]{3}"
    generate: expression
    required: true
  - name: POSTGRES_PASSWORD
    displayName: PostgreSQL Password
    description:
      A minimum 16 character password that is generated in the target database,
      and then copied over into this field.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: POSTGRES_DATABASE
    displayName: PostgreSQL Database Name
    description: The database that will be used by Redash
    value: "redash"
    required: true
  - name: REDIS_PASSWORD
    displayName: Redis Password
    description: Password for Redis that will be used by Redash
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
