{{- if and .Values.provisioner.serviceAccount.enabled (eq .Release.Namespace .Values.provisioner.namespace) }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-provisioner
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4 }}
  namespace: {{ .Values.provisioner.namespace }}

{{ end }}
