{{ if .Values.provisioner.serviceAccount.enabled }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-provisioner
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-provisioner
    namespace: {{ .Values.provisioner.namespace }}


{{ end }}
