{{- if and .Values.linter.serviceAccount.enabled (eq .Release.Namespace .Values.provisioner.namespace)}}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-linter
  labels: {{ include "crunchy-postgres-tools.labels" . | nindent 4}}
  namespace: {{ .Values.linter.namespace }}

{{ end }}
