{{ if and .Values.deployer.serviceAccount.enabled (ne .Release.Namespace .Values.provisioner.namespace) }}

apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4}}
  annotations:
    openshift.io/description: A user who can deploy applications
    openshift.io/reconcile-protect: "false"
  name: {{ or .Values.deploymentName .Release.Name }}-deployer
rules:
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreamtags
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreamtags
    verbs:
      - delete
  - apiGroups:
      - project.openshift.io
      - ""
    attributeRestrictions: null
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - replicationcontrollers
      - persistentvolumeclaims
      - services
      - secrets
      - configmaps
      - endpoints
      - pods
      - pods/exec
    verbs:
      - watch
      - list
      - get
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - pods/status
      - pods/log
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - apps.openshift.io
    attributeRestrictions: null
    resources:
      - deploymentconfigs
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - apps
    attributeRestrictions: null
    resources:
      - statefulsets
    verbs:
      - get
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - route.openshift.io
    attributeRestrictions: null
    resources:
      - routes
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - template.openshift.io
    attributeRestrictions: null
    resources:
      - processedtemplates
    verbs:
      - create
  - apiGroups:
      - route.openshift.io
      - ""
    attributeRestrictions: null
    resources:
      - routes/custom-host
    verbs:
      - create
  - apiGroups:
      - batch
    attributeRestrictions: null
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - create
      - update
      - patch
      - delete
      - watch
      - list
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "rbac.authorization.k8s.io"
      - "authorization.openshift.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters
    verbs:
      - get
      - create
      - update
      - patch
      - delete
{{ end }}
