{{ if and .Values.deployer.serviceAccount.enabled (ne .Release.Namespace .Values.provisioner.namespace) }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ or .Values.deploymentName .Release.Name }}-deployer
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4}}
  namespace: {{ .Release.namespace }}

{{ end }}
