{{ if and .Values.deployer.serviceAccount.enabled (ne .Release.Namespace .Values.provisioner.namespace) }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ or .Values.deploymentName .Release.Name }}-deployer
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ or .Values.deploymentName .Release.Name }}-deployer
subjects:
  - kind: ServiceAccount
    name: {{ or .Values.deploymentName .Release.Name }}-deployer
    namespace: {{ .Release.namespace }}

{{ end }}
