# Pod to mount the backup PVC in test for review or manual pruning.
# Usage:
#   oc apply -f tools/backup-review-pod-test.yaml -n a12c97-test
#   oc rsh pvc-cleanup -n a12c97-test
#   # ... run du -h /mnt/*, ls, or pruning commands ...
#   oc delete pod pvc-cleanup -n a12c97-test
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-cleanup
  namespace: a12c97-test
spec:
  containers:
    - name: cleanup
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /mnt
          name: target
  volumes:
    - name: target
      persistentVolumeClaim:
        claimName: backup-a12c97-test
