---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: app
  app.kubernetes.io/instance: "${APP_NAME}-${JOB_NAME}"
  app.kubernetes.io/managed-by: jenkins
  app.kubernetes.io/name: nodejs
  app.kubernetes.io/part-of: "${APP_NAME}-${JOB_NAME}"
  app: "${APP_NAME}-${JOB_NAME}"
  template: "${REPO_NAME}-app-dc-template"
metadata:
  name: "${REPO_NAME}-app-dc"
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "allow-${APP_NAME}-app-${JOB_NAME}-to-patroni-${JOB_NAME}-cluster"
    spec:
      # Allow app to talk to Patroni cluster
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: "${APP_NAME}-${JOB_NAME}"
                  deploymentconfig: "${APP_NAME}-app-${JOB_NAME}"
                  role: app
          ports:
            - port: 5432
              protocol: TCP
      podSelector:
        matchLabels:
          cluster-name: "${JOB_NAME}"
          statefulset: "patroni-${JOB_NAME}"
          role: master
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "allow-pre-hook-to-patroni-${JOB_NAME}-cluster"
    spec:
      # Allow app pre-hook pods to talk to Patroni cluster
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-pre
          ports:
            - port: 5432
              protocol: TCP
      podSelector:
        matchLabels:
          cluster-name: "${JOB_NAME}"
          statefulset: "patroni-${JOB_NAME}"
          role: master
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"patroni-${JOB_NAME}"}]'
      name: "${APP_NAME}-app-${JOB_NAME}"
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: "${APP_NAME}-${JOB_NAME}"
        deploymentconfig: "${APP_NAME}-app-${JOB_NAME}"
        role: app
      strategy:
        type: Rolling
        resources: {}
        rollingParams:
          timeoutSeconds: 600
          pre:
            failurePolicy: Retry
            execNewPod:
              command:
                - npm
                - run
                - migrate
              containerName: "app"
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: "patroni-${JOB_NAME}-secret"
                - name: DB_HOST
                  value: "patroni-${JOB_NAME}"
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: "patroni-${JOB_NAME}-secret"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: "patroni-${JOB_NAME}-secret"
                - name: SERVER_BASEPATH
                  value: "${ROUTE_PATH}"
      template:
        metadata:
          labels:
            app: "${APP_NAME}-${JOB_NAME}"
            deploymentconfig: "${APP_NAME}-app-${JOB_NAME}"
            role: app
        spec:
          containers:
            - name: app
              image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${REPO_NAME}:${IMAGE_TAG}"
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: "${ROUTE_PATH}/api"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: "${ROUTE_PATH}/api"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 1
                failureThreshold: 1
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: "patroni-${JOB_NAME}-secret"
                - name: DB_HOST
                  value: "patroni-${JOB_NAME}"
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: "patroni-${JOB_NAME}-secret"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: "patroni-${JOB_NAME}-secret"
                - name: FRONTEND_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: VUE_APP_FRONTEND_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: VUE_APP_CONTACT
                  valueFrom:
                    secretKeyRef:
                      key: email
                      name: "${APP_NAME}-contact-secret"

                - name: VUE_APP_HOWTOURL
                  valueFrom:
                    secretKeyRef:
                      key: howtovideourl
                      name: "${APP_NAME}-landingpagevideourls-secret"
                - name: VUE_APP_CHEFSTOURURL
                  valueFrom:
                    secretKeyRef:
                      key: chefstourvideourl
                      name: "${APP_NAME}-landingpagevideourls-secret"
                - name: VUE_APP_CHEFS_GEO_ADDRESS_APIURL
                  valueFrom:
                    secretKeyRef:
                      key: chefsgeoaddressapiurl
                      name: "${APP_NAME}-bcgeoaddress-secret"
                - name: VUE_APP_BC_GEO_ADDRESS_APIURL
                  valueFrom:
                    secretKeyRef:
                      key: bcgeoaddressapiurl
                      name: "${APP_NAME}-bcgeoaddress-secret"
                - name: SERVER_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: SERVER_KC_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: "${APP_NAME}-keycloak-secret"
                - name: SERVER_KC_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: "${APP_NAME}-keycloak-secret"
                - name: SC_CS_CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: ches_client_id
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: ches_client_secret
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CDOGS_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: cdogs_client_id
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CDOGS_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: cdogs_client_secret
                      name: "${APP_NAME}-sc-cs-secret"
                - name: FILES_OBJECTSTORAGE_ACCESSKEYID
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: "${APP_NAME}-objectstorage-secret"
                - name: FILES_OBJECTSTORAGE_SECRETACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: "${APP_NAME}-objectstorage-secret"
                - name: APITOKEN
                  valueFrom:
                    secretKeyRef:
                      key: mailapitoken
                      name: "chefs-${JOB_NAME}-secret"
                # - name: SERVER_LOGFILE
                #   value: "/var/log/app.log"
              envFrom:
                - configMapRef:
                    name: "${APP_NAME}-frontend-config"
                - configMapRef:
                    name: "${APP_NAME}-sc-config"
                - configMapRef:
                    name: "${APP_NAME}-server-config"
                - configMapRef:
                    name: "${APP_NAME}-service-config"
                - configMapRef:
                    name: "${APP_NAME}-files-config"
                - configMapRef:
                    name: "${APP_NAME}-custombcaddressformiocomponent-config"
              # volumeMounts:
              #   - name: log-storage
              #     mountPath: /var/log
            # Fluent-bit log aggregator/forwarder
            # - name: fluent-bit
            #   image: docker.io/fluent/fluent-bit:1.8
            #   imagePullPolicy: IfNotPresent
            #   livenessProbe:
            #     httpGet:
            #       path: /
            #       port: 2020
            #       scheme: HTTP
            #     initialDelaySeconds: 10
            #     timeoutSeconds: 1
            #     failureThreshold: 3
            #   ports:
            #     - containerPort: 2020
            #       name: metrics
            #       protocol: TCP
            #     - containerPort: 80
            #       name: http-plugin
            #       protocol: TCP
            #   readinessProbe:
            #     httpGet:
            #       path: /
            #       port: 2020
            #       scheme: HTTP
            #     initialDelaySeconds: 10
            #     timeoutSeconds: 1
            #     failureThreshold: 3
            #   resources:
            #     requests:
            #       cpu: "${LOGGING_CPU_REQUEST}"
            #       memory: "${LOGGING_MEMORY_REQUEST}"
            #     limits:
            #       cpu: "${LOGGING_CPU_LIMIT}"
            #       memory: "${LOGGING_MEMORY_LIMIT}"
            #   env:
            #     - name: AWS_ACCESS_KEY_ID
            #       valueFrom:
            #         secretKeyRef:
            #           key: username
            #           name: "${APP_NAME}-aws-kinesis-secret"
            #     - name: AWS_SECRET_ACCESS_KEY
            #       valueFrom:
            #         secretKeyRef:
            #           key: password
            #           name: "${APP_NAME}-aws-kinesis-secret"
            #   volumeMounts:
            #     - name: log-storage
            #       mountPath: /var/log
            #     - name: fluent-bit-config
            #       mountPath: /fluent-bit/etc/
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
            - name: log-storage
              emptyDir: {}
            # - name: fluent-bit-config
            #   configMap:
            #     name: fluent-bit-config
      test: false
      triggers:
        - type: ConfigChange
        # - imageChangeParams:
        #     automatic: true
        #     containerNames:
        #       - app
        #     from:
        #       kind: ImageStreamTag
        #       name: "${REPO_NAME}-app:${JOB_NAME}"
        #       namespace: "${NAMESPACE}"
        #   type: ImageChange
  #- apiVersion: v1
  #  kind: PersistentVolumeClaim
  #  metadata:
  #    name: "${APP_NAME}-data-${JOB_NAME}"
  #  spec:
  #    accessModes:
  #      - ReadWriteMany
  #    storageClassName: "${DATA_PERSISTENT_VOLUME_CLASS}"
  #    resources:
  #      requests:
  #        storage: "${DATA_VOLUME_CAPACITY}"
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${APP_NAME}-app-${JOB_NAME}"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: "${APP_NAME}-${JOB_NAME}"
        deploymentconfig: "${APP_NAME}-app-${JOB_NAME}"
        role: app
      sessionAffinity: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${APP_NAME}-app-${JOB_NAME}"
    spec:
      host: "${ROUTE_HOST}"
      path: "${ROUTE_PATH}"
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${APP_NAME}-app-${JOB_NAME}"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: APP_NAME
    description: Application name
    displayName: Application name
    required: true
  - name: ROUTE_HOST
    description: The host the route will use to expose service outside cluster
    displayName: Route host
    required: true
  - name: ROUTE_PATH
    description: Configure the route path (ex. /pr-5 or /app), also used for VUE_APP_FRONTEND_BASEPATH
    displayName: Route path
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: IMAGE_REGISTRY
    description: The container registry
    displayName: Docker Image Registry
    required: true
    value: ghcr.io
  - name: IMAGE_NAMESPACE
    description: The image namespace
    displayName: Docker Image Namespace
    required: true
    value: bcgov
  - name: IMAGE_TAG
    description: The specific image tag to deploy
    displayName: Docker Image Tag
    required: true
    value: latest
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'wfezkf-dev')
    displayName: Target Namespace
    required: true
  - name: REPO_NAME
    description: Application repository name
    displayName: Repository Name
    required: true
  - name: CPU_LIMIT
    description: Limit Peak CPU per pod (in millicores ex. 1000m)
    displayName: CPU Limit
    value: 250m
  - name: CPU_REQUEST
    description: Requested CPU per pod (in millicores ex. 500m)
    displayName: CPU Request
    value: 50m
  - name: MEMORY_LIMIT
    description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
    displayName: Memory Limit
    value: 1Gi
  - name: MEMORY_REQUEST
    description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
    displayName: Memory Request
    value: 256Mi
  - name: DATA_DIR
    description: Path to data directory
    displayName: Directory to mount for data files
    required: true
    value: "/mnt/app/data"
  - name: DATA_VOLUME_CAPACITY
    description: Volume space available for Data
    displayName: Data Volume Capacity (use M or G, not Mi or Gi)
    required: true
    value: 21M
  - name: DATA_PERSISTENT_VOLUME_CLASS
    description: The storage class of the volume
    displayName: Persistent Volume Class name
    value: netapp-file-standard
  # parameters for fluent-bit
  - name: LOGGING_CPU_LIMIT
    description: Limit Peak CPU per pod (in millicores ex. 1000m)
    displayName: CPU Limit
    value: 50m
  - name: LOGGING_CPU_REQUEST
    description: Requested CPU per pod (in millicores ex. 500m)
    displayName: CPU Request
    value: 10m
  - name: LOGGING_MEMORY_LIMIT
    description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
    displayName: Memory Limit
    value: 64Mi
  - name: LOGGING_MEMORY_REQUEST
    description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
    displayName: Memory Request
    value: 16Mi
