---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Application secrets generation
    openshift.io/display-name: CHEFS application secrets
    openshift.io/long-description: This template creates secrets to be used by CHEFS app.
    tags: chefs
  name: chefs-app-secret
labels:
  app.kubernetes.io/instance: "${INSTANCE}"
  app.kubernetes.io/component: app
  app.kubernetes.io/name: chefs
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "12"
  cluster-name: "${INSTANCE}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${NAME}-${INSTANCE}-secret"
    stringData:
      mailapitoken: "${MAIL_API_TOKEN}"
parameters:
  - name: NAME
    description: The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
    value: chefs
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
  - name: MAIL_API_TOKEN
    description: The token used to protect mail notification API endpoint
    displayName: Mail API token
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
