apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjobpi"
        spec:
        containers:
          - name: my-container
            image: docker.io/curlimages/curl:7.82
            env:
            - name: URL
              valueFrom:
              configMapKeyRef:
                name: endpoints-configmap
                key: mail_notification_uri
            - name: APITOKEN
              valueFrom:
              secretKeyRef:
                name: apitokens
                key: mailapitoken
            command:
              - sh
              - '-c'
            args:
              - >-
               curl -X GET -ks
               $URL
               -H "apikey: $APITOKEN"
               -H "Content-Type: application/json"
      restartPolicy: OnFailure
