---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: app
  app.kubernetes.io/instance: "${APP_NAME}-${JOB_NAME}"
  app.kubernetes.io/managed-by: github
  app.kubernetes.io/name: nodejs
  app.kubernetes.io/part-of: "${APP_NAME}-${JOB_NAME}"
  app: "${APP_NAME}-${JOB_NAME}"
  template: "chefs-css-cm-template"
metadata:
  name: "chefs-css-cm"
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APP_NAME}-${JOB_NAME}-common-services"
    data:
      VITE_CS_CSS_API_URL: "${ROUTE_PATH}/api/v1/cs/css/idir/users"
parameters:
  - name: APP_NAME
    description: Application name
    displayName: Application name
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: ROUTE_PATH
    description: Route Subpath Mount point
    displayName: Route Path
    required: true
    default: "/app"
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'wfezkf-dev')
    displayName: Target Namespace
    required: true