version: "3.7"

networks:
  chefs-net:
    driver: "bridge"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:7.0.1
    restart: always
    environment:
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /tmp/keycloak-local-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: "${KEYCLOAK_USER}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
    networks:
      - chefs-net
    ports:
      - "${KEYCLOAK_HOST_HTTP_PORT}:8080"
      - "${KEYCLOAK_HOST_HTTPS_PORT}:8443"
    volumes:
      - ./settings/keycloak-local-realm.json:/tmp/keycloak-local-realm.json
      - ./settings/keycloak-local-user.sh:/tmp/keycloak-local-user.sh

  formio:
    container_name: formio
    image: formio/formio-enterprise
    restart: always
    environment:
      LICENSE: "${FORMIO_LICENSE}"
      MONGO: "${FORMIO_MONGO}"
      PRIMARY: "true"
    networks:
      - chefs-net
    ports:
      - "3000:80"
