import orgbook from './OrgBook/Orgbook';
import simplecheckbox from './SimpleCheckbox/Component';
import simplecheckboxes from './SimpleCheckboxes/Component';
import simpledatetime from './SimpleDateTime/Component';
import simpleday from './SimpleDay/Component';
import simpleemail from './SimpleEmail/Component';
import simpleheading from './SimpleHeading/Component';
import simplenumber from './SimpleNumber/Component';
import simpleparagraph from './SimpleParagraph/Component';
import simplephonenumber from './SimplePhoneNumber/Component';
import simpleradios from './SimpleRadios/Component';
import simpleselect from './SimpleSelect/Component';
import simpletextarea from './SimpleTextArea/Component';
import simpletextfield from './SimpleTextField/Component';
import simpletime from './SimpleTime/Component';
declare const _default: {
    orgbook: typeof orgbook;
    simplecheckbox: typeof simplecheckbox;
    simplecheckboxes: typeof simplecheckboxes;
    simpledatetime: typeof simpledatetime;
    simpleday: typeof simpleday;
    simpleemail: typeof simpleemail;
    simpleheading: typeof simpleheading;
    simplenumber: typeof simplenumber;
    simpleparagraph: typeof simpleparagraph;
    simplephonenumber: typeof simplephonenumber;
    simpleradios: typeof simpleradios;
    simpleselect: typeof simpleselect;
    simpletextarea: typeof simpletextarea;
    simpletextfield: typeof simpletextfield;
    simpletime: typeof simpletime;
};
export default _default;
