import orgbook from './OrgBook/Orgbook';
import simplebtnreset from './SimpleButtonReset/Component';
import simplebtnsubmit from './SimpleButtonSubmit/Component';
import simplecheckbox from './SimpleCheckbox/Component';
import simplecheckboxes from './SimpleCheckboxes/Component';
import simplecols2 from './SimpleColumns2/Component';
import simplecols3 from './SimpleColumns3/Component';
import simplecols4 from './SimpleColumns4/Component';
import simplecontent from './SimpleContent/Component';
import simpledatetime from './SimpleDateTime/Component';
import simpleday from './SimpleDay/Component';
import simpleemail from './SimpleEmail/Component';
import simplefieldset from './SimpleFieldSet/Component';
import simplefile from './SimpleFile/Component';
import simpleheading from './SimpleHeading/Component';
import simplenumber from './SimpleNumber/Component';
import simplepanel from './SimplePanel/Component';
import simpleparagraph from './SimpleParagraph/Component';
import simplephonenumber from './SimplePhoneNumber/Component';
import simpleradios from './SimpleRadios/Component';
import simpleselect from './SimpleSelect/Component';
import simpletabs from './SimpleTabs/Component';
import simpletextarea from './SimpleTextArea/Component';
import simpletextfield from './SimpleTextField/Component';
import simpletime from './SimpleTime/Component';
declare const _default: {
    orgbook: typeof orgbook;
    simplebtnreset: typeof simplebtnreset;
    simplebtnsubmit: typeof simplebtnsubmit;
    simplecheckbox: typeof simplecheckbox;
    simplecheckboxes: typeof simplecheckboxes;
    simplecols2: typeof simplecols2;
    simplecols3: typeof simplecols3;
    simplecols4: typeof simplecols4;
    simplecontent: typeof simplecontent;
    simpledatetime: typeof simpledatetime;
    simpleday: typeof simpleday;
    simpleemail: typeof simpleemail;
    simplefieldset: typeof simplefieldset;
    simplefile: typeof simplefile;
    simpleheading: typeof simpleheading;
    simplenumber: typeof simplenumber;
    simplepanel: typeof simplepanel;
    simpleparagraph: typeof simpleparagraph;
    simplephonenumber: typeof simplephonenumber;
    simpleradios: typeof simpleradios;
    simpleselect: typeof simpleselect;
    simpletabs: typeof simpletabs;
    simpletextarea: typeof simpletextarea;
    simpletextfield: typeof simpletextfield;
    simpletime: typeof simpletime;
};
export default _default;
