name: Pull Request Closed

env:
  ACRONYM: chefs

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Pull Request Number:"
        type: string
        required: true
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.pr-number || github.ref }}
  cancel-in-progress: true

jobs:
  remove-pr-dev:
    name: Remove PR build from dev namespace
    if: "! github.event.pull_request.head.repo.fork"
    environment:
      name: pr
      url: https://${{ env.ACRONYM }}-dev-pr-${{ github.event.inputs.pr-number }}.apps.silver.devops.gov.bc.ca
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to OpenShift Cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ vars.NAMESPACE_PREFIX }}-dev
      - name: Remove PR Deployment
        shell: bash
        run: |
          oc delete -n ${{ vars.NAMESPACE_PREFIX }}-dev all,secret,networkpolicy,rolebinding --selector app=${{ env.ACRONYM }}-pr-${{ github.event.inputs.pr-number }}
          oc delete -n ${{ vars.NAMESPACE_PREFIX }}-dev all,svc,cm,sa,role,secret --selector cluster-name=pr-${{ github.event.inputs.pr-number }}
      - name: Remove Release Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: release
          delete: true
      - name: Remove Github Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: pr
          onlyRemoveDeployments: true
          token: ${{ secrets.GITHUB_TOKEN }}
