name: Push

env:
  ACRONYM: chefs

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Push
        uses: ./.github/actions/build-push-container
        with:
          context: .
          image_name: ${{ vars.APP_NAME }}
          github_username: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_contact: ${{ secrets.VUE_APP_CONTACT }}

  deploy-dev:
    name: Deploy to Dev
    environment:
      name: dev
      url: https://${{ env.ACRONYM }}-dev.apps.silver.devops.gov.bc.ca/app
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Dev
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ vars.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: dev
          job_name: master
          namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
          namespace_environment: dev
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          server_host: ${{ vars.SERVER_HOST }}
          route_path: /app

  deploy-test:
    name: Deploy to Test
    environment:
      name: test
      url: https://${{ env.ACRONYM }}-test.apps.silver.devops.gov.bc.ca/app
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-dev
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Test
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ vars.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: test
          job_name: master
          namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
          namespace_environment: test
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          server_host: ${{ vars.SERVER_HOST }}
          route_path: /app

  deploy-prod:
    name: Deploy to Prod
    environment:
      name: prod
      url: https://${{ env.ACRONYM }}.apps.silver.devops.gov.bc.ca/app
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-dev
      - deploy-test
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Prod
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ vars.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: prod
          job_name: master
          namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
          namespace_environment: prod
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          server_host: ${{ vars.SERVER_HOST }}
          route_path: /app
